# ODM CircleCI 2.0 configuration file
#
version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
    parallelism: 1
    working_directory: ~/odm
    branches:
      only:
        - travis
    steps:
      - checkout
      - run: export DEBIAN_FRONTEND=noninteractive && echo zdata tzdata/Areas select Europe >> preseed.txt && echo tzdata tzdata/Zones/Europe select London >> preseed.txt && debconf-set-selections preseed.txt && apt-get update && apt-get -y install software-properties-common && ./configure.sh install 
